name: CD
on: [push]
#  push:
#    tags:
#      - '*'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare GPG
        env:
          MVN_GPG_SECRING: ${{ secrets.MVN_GPG_SECRING }}
        run: |
          echo $MVN_GPG_SECRING | base64 --decode > secring.gpg
      - name: Build & Upload to Maven
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          MVN_GPG_KEYID: ${{ secrets.MVN_GPG_KEYID }}
          MVN_GPG_PASSWORD: ${{ secrets.MVN_GPG_PASSWORD }}
        run: |
          VERSION_NAME=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          VERSION_NAME=1.0.0-SNAPSHOT
          echo "Deploying ${VERSION_NAME} to maven..."
          ./gradlew -PVERSION_NAME="${VERSION_NAME}" -Psigning.keyId="${MVN_GPG_KEYID}" -Psigning.gnupg.keyName="${MVN_GPG_KEYID}" -Psigning.gnupg.passphrase="${MVN_GPG_PASSWORD}" -Psigning.password="${MVN_GPG_PASSWORD}" -Psigning.secretKeyRingFile="secring.gpg" clean build uploadArchives
