name: CD
on:
  push:
    tags:
      - '*'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      - name: Upload to Maven
        run: |
          VERSION_NAME=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "Deploying ${VERSION_NAME} to maven..."
          ./gradlew -PVERSION_NAME=${VERSION_NAME} clean build uploadArchives
