name: CD
on:
  push:
    tags:
      - '*'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      - name: Prepare GPG
        env:
          MVN_GPG_SECRING: ${{ secrets.MVN_GPG_SECRING }}
        run: |
          echo $MVN_GPG_SECRING | base64 > ~/.gnupg/secring.kbx
      - name: Upload to Maven
        env:
          MVN_GPG_KEYID: ${{ secrets.MVN_GPG_KEYID }}
          MVN_GPG_PASSWORD: ${{ secrets.MVN_GPG_PASSWORD }}
        run: |
          VERSION_NAME=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "Deploying ${VERSION_NAME} to maven..."
          ./gradlew -PVERSION_NAME=${VERSION_NAME} -Psigning.keyId=${MVN_GPG_KEYID} -Psigning.password=${MVN_GPG_PASSWORD} -Psigning.secretKeyRingFile="~/.gnupg/secring.kbx" clean build uploadArchives
